stages:
  - build
  - test
  - deploy

build-job:
  tags:
    - e3208
  stage: build
  script:
    - ls
    - cd cwm
    - echo build number CI_BUILD_REF
    - ./gradlew build deployReports -Dorg.gradle.project.buildNumber=1

  only:
    - v2

