stages:
  - build
  - test
  - deploy

build-job:
  tags:
    - atria
  stage: build
  script:
    - cd cowem-plugin
    - export BUILD_LABEL="`date -Idate` $CI_BUILD_REF"
    - ./gradlew build deployReports -Dorg.gradle.project.buildNumber="$BUILD_LABEL"
  only:
    - master

