Title: Course Website Overview and Instructions (secondary)
Author: Steven Zeil
Date: @docModDate@
TOC: yes

Some words of explanation about how I organize and maintain course websites.

The website is a collection of primary and secondary
documents.

_Primary documents_ carry lots of content and are
stored with each in its own directory. Primary documents can be
converted from source documents in [Markdown](../markdown/index.html)
into a variety of a variety of HTML-based output formats.

Also, supported, but deprecated, is support for source documents in
DocBook or LaTeX, converted into HTML or PDF.

_Secondary documents_ are shorter documents that are often intended to
accompany a primary document. For example, a set of lecture notes (a
primary document) on sorting algorithms might be accompanied by
several C++ source code files, each of which will be converted to an
HTML document residing in the same directory as the primary.

